title: BitNinja Technology

# Exclude dev files from the Jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yml
  - vendor/

# Markdown and Syntax Highlighting Configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: true      # Automatically convert single line breaks to <br />